language: java
sudo: false
jdk:
- oraclejdk8
git:
  submodules: false
install: true
script: "./travis.sh"
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'
    - '$HOME/jvm'
notifications:
  email: false
  webhooks:
    - secure: "QvKngjMLM14D5dguSgK5kQhXUi5FFJliH2iq9pu8Gim4y0cOufxNBlYs/fiV9cB6TAXhU0L2/QHWhbYKqFjrqM+xRUV4EtokUeoXmG9x6HJk83XJxtPLu1lmpp5O6e4NIw4OGXcGLCFfx6MQmsIDezJBIdFkiXwtaJIm2gKBBr/fgaygfB04ST8i4I1mavqK7fbfWaQpjG2acvGKH5L53BIMsJsO/F22fdowN8b3l2lLFln0nzQxENXeGSluKMTUMN+gjVdSwIXpMeCrYWKF46/HvazCPqt+QiK6LZr006Fiy/oPaC7B8p5k+RoYAk4UNs85iSi6RejuJH8xB/nu7t3e+q22URZGDC16sza/2xBZs1+2eLCqNAJS/lt3yPHJ8Oy8u84bAUonhIP2+ClrxB1WBScZya3NBkmmcAiwZ9u7av+r+r7BXdVkP8QuIfA8xpCFgqJBDzxSyLOrAsrRwZkao9ix1Z4JrHmXmj+lCZA7jO1H6xMi5wwGj2vR90941Xci6Mmfm9YhfYk47nW33NLhbCQ7Baz9hz7K44DWs5blP4YW5b8abAff3luFIxQQMF6hrsPYlS/XHe4I0Wi2eCJWHXGU+s0eLTwbx7oQub16EdSQq03a5k3lNotNTRhuQ3SOzubCRZGO+fkDwM/av1sh2GRyIcDIPhxrTcm1XWE="
  on_start: always
